[[headers]]
for = "/*.vcf"

  [headers.values]
  Content-Type = "text/x-vcard"

[[redirects]]
from = "/gallery/:gallery/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"
