[[headers]]
for = "/*.vcf"
  [headers.values]
  Content-Type = "text/x-vcard"

[build.environment]
NETLIFY_IMAGE_CDN = "true"

[images]
remote_images = ["https://ik.imagekit.io/tony/.*"]

[dev]
command = "yarn dev"
